### ISSUE TITLE
Stuck at DNS entry for etcd

### ISSUE THREAD

**Issue by malagant** [slauger/hcloud-okd4#64]
Fantastic project. Thanks for the great effort.

Today I faced a problem with creating DNS entries at cloudflare.

```
Error: Failed to create record: error from makeRequest: HTTP status 400: content "{\"result\":null,\"success\":false,\"errors\":[{\"code\":1004,\"message\":\"DNS Validation Error\",\"error_chain\":[{\"code\":9101,\"message\":\"service is a required data field.\"}]}],\"messages\":[]}"

on dns.tf line 52, in resource "cloudflare_record" "dns_srv_etcd":
52: resource "cloudflare_record" "dns_srv_etcd" {
make: *** [Makefile:86: infrastructure] Error 1
bash-5.0#```

The previous commit worked like a charm.

Any hint?

**Comment by slauger** [comment]
I'm already seen this error - that's why i switched the code recently from the data block to the value parameter. When i remember correctly there was a bug in the Terraform Cloudflare provider.

https://github.com/slauger/hcloud-okd4/commit/8ee99556d6eec49f90495f9ae975cbed28c084b5#diff-5b57b22983407019f012a47a87a23594

Maybe now it's related to the new Terraform version. So commit 60eade298479c040d7c9eb8c7ad1a27c30788a49 works for you?

**Comment by malagant** [comment]
I fixed it with the content from line 52 to the end of https://github.com/slauger/hcloud-okd4/blob/995046369d12b47b576d87fedf3342625a93263c/terraform/dns.tf

This worked a few seconds ago.

**Comment by slauger** [comment]
Ok, seems like that Cloudflare changed the behavior of the api. It seems that it's no longer possible to leave out the `data` block for `SRV` records. Well, this breaks my recent workaround... I couldn't reproduce the initial bug, so i switch back to the data block.

Thanks for your feedback!

**Comment by malagant** [comment]
Thank you for the great effort. I am interested in contribution. So if you have some ideas, please let me know.

**Comment by slauger** [comment]
Currently the main issue is the networking. I need to setup all nodes with a public ip address, because of the weird implementation of internal networks in the hcloud. There is no ability to deploy a firewall/security group in the hcloud. Because of that internal ports are open to the public internet (e.g. prometheus) - which results in a abuse message from Hetzner after a few days (because of the exposed portmapper port).

We need local firewall (e.g. iptables/nftables) or a two-armed deployment. I already played around with the NetworkManager, but i couldn't find a working solution here. If you have a idea here, please let me know.

Until i have a solution here i stick to OpenShift on GCP for my training and demo environments.

Another problem is the poor storage I/O performance of the hcloud. Sometimes the bootstrap is successful, sometimes not. It's really annoying.

**Comment by malagant** [comment]
That's exactly what I experienced in the last weeks. I'll have a look. Maybe there comes something to my mind.
